export const ADMIN = {
    FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILED : 'FETCH_USERS_FAILED',
    FETCH_USER_REQUEST : 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS : 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILED : 'FETCH_USER_FAILED',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED : 'DELETE_USER_FAILED',
    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_REQUEST:'CREATE_USER_REQUEST',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED'
}