export const USER = {
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_FAILED : "SIGNUP_FAILED",
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILED : 'LOGOUT_FAILED',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILED : 'LOGIN_FAILED',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
}